spring:
  application:
    name: springcloud-ribbon-comsumer
server:
  port: 9000
eureka:
  client:
   serviceUrl:
     defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}