spring:
  application:
    name: spring-cloud-service-zuul
server:
  port: 8769
eureka:
  client:
   serviceUrl:
     defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: spring-cloud-service-ribbon
    api-b:
      path: /api-b/**
      serviceId: spring-cloud-service-feign
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

