spring:
  application:
    name: springcloud-ribbon-comsumer
server:
  port: 8769
eureka:
  client:
   serviceUrl:
     defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign