server:
  port: 8080
spring:
  application:
    name: springcloud-hello-service
eureka:
  client:
   serviceUrl:
     defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}